using Surf_Cafe.Database;
using Surf_Cafe.Models;

namespace Surf_Cafe.Forms
{
    public partial class LoyaltyForm : Form
    {
        public LoyaltyForm()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Method to check if email is valid then add to customer model.
        /// 
        /// Generated by ChatGpt.
        /// 
        /// Reference:
        /// ChatGPT
        /// OpenAI, 2025. ChatGPT[Computer program]. Version GPT-5 mini.
        /// Available at: https://chat.openai.com
        /// 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnAdd_Click(object sender, EventArgs e)
        {
            string email = tbEmail.Text.Trim();

            if (!IsValidEmail(email))
            {
                MessageBox.Show("Invalid email address.");
                return;
            }

            using (var db = new DBContext())
            {
                var customer = db.Customers.FirstOrDefault(c => c.EmailAddress == email);
                if (customer != null)
                {
                    customer.LoyaltyPoints += 1;
                    db.SaveChanges();
                    MessageBox.Show($"Existing customer found. Added 1 point. Total points: {customer.LoyaltyPoints}", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
                else
                {
                    var newCustomer = new Customer
                    {
                        EmailAddress = email,
                        DateRegistered = DateTime.Now,
                        LoyaltyPoints = 1
                    };

                    db.Customers.Add(newCustomer);
                    db.SaveChanges();
                    MessageBox.Show("New customer added with 1 loyalty point.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
        }

        /// <summary>
        /// Uses EmailAddressAttribute to validate email.
        /// 
        /// Generated by ChatGpt.
        /// 
        /// Reference:
        /// ChatGPT
        /// OpenAI, 2025. ChatGPT[Computer program]. Version GPT-5 mini.
        /// Available at: https://chat.openai.com
        /// 
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        private bool IsValidEmail(string email)
        {
            var emailAttr = new System.ComponentModel.DataAnnotations.EmailAddressAttribute();
            return emailAttr.IsValid(email);
        }

        private void btnBack_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
